#!/bin/sh

usage() {
    echo $(basename "$0"): ERROR: "$@" 1>&2
    echo usage: $(basename "$0") '[-n dir_name] [-p projects_dir] [-c config_name] [session]' 1>&2
    exit 1
}

set -- $(getopt -u -o 'c:n:p:' -- $@) || usage ""

projects_dir=~/projects
session=
dir_name=
config_name=

while :
do
    case "$1" in
        -n) shift; dir_name="$1";;
        -p) shift; projects_dir="$1";;
        -c) shift; config_name="$1";;
        --) break;;
    esac
    shift
done
shift

[ -z $1 ] && usage "You must provide a session name to create or attach"
session=$1

c_opt="$projects_dir/${dir_name:=$session}"

tmux has-session -t $session 2> /dev/null

if [ $? -ne 0 ]; then
    TMUX= tmux new-session -d -s $session -c $c_opt
    if [ -n "$config_name" ]; then
        tmux send-keys -t ${session}.0 "tmux source-file ~/.config/tmux/${config_name}.tmux" ENTER
    fi
fi

if [ -z $TMUX ]; then
    tmux attach-session -t $session:0
else
    tmux switch-client -t $session:0
fi
